resources:
  - url: http://127.0.0.1:5000/project-card.js
    type: module
views:
  - cards:
      - type: custom:project-card
        name: Project Card Development
        entity: sun.sun
        test_gui: true
