resources:
  - url: http://127.0.0.1:5000/display-feed-card.js
    type: module
views:
  - cards:
      - type: custom:display-feed-card
        name: Display-Feed Card Development
        entity: sun.sun
        test_gui: true
